### ISSUE TITLE
VARMAX Work

### ISSUE THREAD

**Issue by aksomers** [amitp06/COVID-19#6]
Kicked off some varmax work in a separate script file and pushed it. The relevant function runs, but i think there are issues because of dimensionality reasons (number of columns/counties > number of days in the time series). We can probably fix in a few ways--limiting the counties, aggregating to state level, maybe some other options?

Anyway, will slowly plug away at this, just wanted to get a bit of a start.

**Comment by amitp06** [comment]
Cool to see. Yeah, running the varmax with a subset of the data is good if that helps. We can reduce the scope based on the limitations of the dimensions.

**Comment by amitp06** [comment]
We're done!
